apiVersion: v1
kind: Pod
metadata:
  labels:
    app: k8s-web-back
  name: k8s-web-back
  namespace: default
spec:
  containers:
    - command:
        - java
        - -jar
        - /app.jar
        - --spring.profiles.active=pro
      image: zhf5201314/k8s-web-backen:v1.0.2
      imagePullPolicy: IfNotPresent
      name: k8s-web-backen
      ports:
        - containerPort: 8093
          name: http
      env:
        - name: PROMETHEUS_API
          value: http://prometheus-k8s.monitoring:9090

---

apiVersion: v1
kind: Service
metadata:
  name: service-k8s-web-back

spec:
  ports:
    - name: name-of-service-port
      port: 8093
      protocol: TCP
      targetPort: http
  selector:
    app: k8s-web-back
  type: ClusterIP