apiVersion: v1
kind: Pod
metadata:
  labels:
    app: k8s-web-back
  name: k8s-web-back
  namespace: default
spec:
  containers:
    - command:
        - java
        - -jar
        - /app.jar
        - --spring.profiles.active=pro
      image: zhf5201314/k8s-web-backen
      imagePullPolicy: IfNotPresent
      name: k8s-web-backen
      ports:
        - containerPort: 8093
          name: http