apiVersion: v1
kind: Pod
metadata:
  labels:
    app: cputest
  name: cputest-replace
  namespace: default
spec:
  schedulerName: crane-scheduler
  containers:
  - command:
    - java
    - -jar
    - /root/entrance.jar
    image: zhf5201314/cputest:v1.0.1
    imagePullPolicy: IfNotPresent
    name: memtest
#    resources:
#      limits:
#        cpu: 500m
#        memory: 500Mi
#      requests:
#        cpu: "500m"
#        memory: 500Mi