apiVersion: scheduler.policy.crane.io/v1alpha1
kind: DynamicSchedulerPolicy
spec:
  syncPolicy:
    ##cpu usage
    - name: cpu_usage_avg_5m
      period: 3m
    - name: cpu_usage_max_avg_1h
      period: 3m
    - name: cpu_usage_max_avg_1d
      period: 3m
    ##memory usage
    - name: mem_usage_avg_5m
      period: 3m
    - name: mem_usage_max_avg_1h
      period: 3m
    - name: mem_usage_max_avg_1d
      period: 3m


  predicate:
    ##cpu usage
    - name: cpu_usage_avg_5m
      maxLimitPecent: 0.65
    - name: cpu_usage_max_avg_1h
      maxLimitPecent: 0.75
    ##memory usage
    - name: mem_usage_avg_5m
      maxLimitPecent: 0.65
    - name: mem_usage_max_avg_1h
      maxLimitPecent: 0.75

  priority:
    ###score = sum(() * weight) / len,  0 <= score <= 10
    ##memory usage
    ##memory usage
    - name: mem_usage_avg_5m
      weight: 0.8
    - name: mem_usage_max_avg_1h
      weight: 0.1
    - name: mem_usage_max_avg_1d
      weight: 0.1

  hotValue:
    - timeRange: 5m
      count: 5
    - timeRange: 1m
      count: 2
