server:
  port: 8093
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://gz-cynosdbmysql-grp-q0u8k5ub.sql.tencentcdb.com:20559/lover?serverTimezone=GMT%2B8
    username: root
    password: zhf5201314..
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
my:
  config:
    savePath: E:/picture4
    httpPrefix: https://touxiang.gzucmrepair.top/api