spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${my.config.savePath}
  servlet:
    multipart:
      max-request-size: 4096MB
      max-file-size: 4096MB
  jpa:
    show-sql: true
server:
  servlet:
    session:
      timeout: 3600
# JACKSON (JacksonProperties)

